Rel1 39 2.6.6
Open-CSP/PageSync pull request #15
Opened 2024-10-09 09:21 UTC by Designburo

Adding an Analyze function to the maintenance script. It will check the PageSync files; the index file and gives detailed information on any discrepancies.

2024-10-09 09:21 UTC, Designburo commented
I will do one more push to add all texts to i18n

2024-10-10 09:40 UTC, Designburo commented
Added all to i18n.

2025-01-21 10:48 UTC, marijnvanwezel requested changes

2025-01-21 10:48 UTC, marijnvanwezel commented on maintenance/WSps.maintenance.php
> +		if ( empty( PSConfig::$config ) ) {
Why not `!PSConfig::$config`?

2025-01-21 10:48 UTC, marijnvanwezel commented on maintenance/WSps.maintenance.php
> +			if ( empty( PSConfig::$config ) ) {
Same as above.

2025-01-21 10:48 UTC, marijnvanwezel commented on src/Core/PSAnalyzer.php
> +		$perc = round( ( $done * 100 ) / $total );
This errors if `$total` is zero.

2025-01-21 10:48 UTC, marijnvanwezel commented on src/Core/PSAnalyzer.php
> +			if ( $fileBaseNameInfo['status'] === false ) {
```suggestion
			if ( !$fileBaseNameInfo['status'] ) {
```

2025-01-21 10:48 UTC, marijnvanwezel commented on src/Core/PSAnalyzer.php
> +				if ( $slotFile === false ) {
```suggestion
				if ( !$slotFile ) {
```

2025-01-21 10:48 UTC, marijnvanwezel commented on src/Core/PSAnalyzer.php
> +		if ( $indexList === false ) {
```suggestion
		if ( !$indexList ) {
```

2025-01-21 10:48 UTC, marijnvanwezel commented on src/Core/PSAnalyzer.php
> +		if ( empty( $this->indexList ) === false && empty( $this->serverFullList ) ) {
```suggestion
		if ( !empty( $this->indexList ) && empty( $this->serverFullList ) ) {
```

2025-02-04 13:35 UTC, Designburo commented on src/Core/PSAnalyzer.php
> +		$perc = round( ( $done * 100 ) / $total );
It will never reach this function is total is 0

2025-02-04 13:44 UTC, merged